### ISSUE TITLE
No URDF file For SDA10F robot

### ISSUE THREAD

**Issue by clementguerin1** [ros-industrial/motoman#206] opened 2018-04-25 09:31 UTC
Hi,

I am not sure of it, but when I look in the folder motoman_sda10f_support there should be a file an.urdf but it is not here. I am not very familiar of ROS and robot generally, but I am enough sure that we need to have a file .urdf here.

Bwaki

**Comment by gavanderhoorn** [comment] 2018-04-25 09:37
Your are correct that there are no `.urdf` files. But that is 'by design': we provide [xacro](http://wiki.ros.org/xacro) files, which, if necessary, can be converted to urdfs using the `xacro` tool.

**Comment by gavanderhoorn** [comment] 2018-04-25 09:38
As this is not an issue with the pkgs in this repository, I'm going to close this issue.

Feel free to keep commenting on it though.

**Closed as completed by gavanderhoorn** 2018-04-25 09:38 UTC
