### ISSUE TITLE
Choppy motion of ROS controlled yaskawa GP8 robot

### ISSUE THREAD

**Issue by iom12** [ros-industrial/motoman#386] opened 2021-02-03 16:45 UTC
I'm trying to command the GP8 robot via ROS / motoplus, sending it a sequence of trajectories (teleoperation). Each trajectory is made up of 2 points (The first point is the robot's current joint configuration. The second is the target joint configuration.). I get a non-continuous movement of the robot. I have a doubt that the frequency of sending messages from the controller to the actuators is the cause (if it is low). Is there any way to find out this frequency? Can we modify it? I thank you for your feedback.

**ROS version**: ROS Melodic
**Computer operation system**: Ubuntu 18.04.5 LTS
**motoman git**: kinetic-devel branch
**Controller**: yrc1000
**Installation MotoROS**: Yaskawa did it for me.
**Start command**: roslaunch motoman_gp8_support robot_interface_streaming_gp8.launch robot_ip:=. *. * . controller:=yrc1000 Then I run a ROS node which publishes my two-point trajectory into "/joint_trajectory_action topic".
**Trajectory generation**: I send a goal trajectory of type control_msgs::FollowJointTrajectoryGoal. It is composed of two points whose velocities are zeros. This goal is sent to the "/joint_trajectory_action" topic. First trajectory point corresponds to the actual behavior of the robot. It is got from /joint_states topic. Second point is defined by the user respecting the acceptable range limits. Typically, I send the second point using rqt_joint_trajectory_controller
**Connection**: The controller is connected to the computer by ethernet.

**Comment by gavanderhoorn** [comment] 2021-02-03 17:05
I believe this is related to / a follow-up of [Choppy motion of ROS controlled yaskawa robot](https://answers.ros.org/question/370444) on ROS Answers.

> I'm trying to command the GP8 robot via ROS / motoplus, sending it a sequence of trajectories (teleoperation).

`motoman_driver` is not really suited for what you're trying to do. It's possible to use trajectory replacement for these kinds of things, but that's not supported by `motoman_driver` right now. `motoman_driver` is essentially *trajectory based*, ie: it consumes trajectories, not individual position setpoints.

> I send a goal trajectory of type control_msgs::FollowJointTrajectoryGoal. It is composed of two points whose velocities are zeros.

I'm pretty sure this is the cause of your problem. Setting `velocities` to zero will lead to stop-and-go behaviour.

You could look at #215, but note that it's not integrated with the current state of the driver.

For ROS 2, you could potentially look at what's discussed in #359. There's nothing really ROS 2 specific about that though, so with some work it could be used in ROS 1 as well.

---

Edit: just to clarify: `motoman_driver` is the ROS part of the driver. MotoROS is the part running on the controller. You are using `motoman_driver`. Without additional changes -- such as those in #215, that's not really suited for tele-operation.

**Comment by iom12** [comment] 2021-02-04 11:16
@gavanderhoorn Thank you for your answer. 
This subject is a follow-up  of [Choppy motion of ROS controlled yaskawa robot ](https://answers.ros.org/question/370444/choppy-motion-of-ros-controlled-yaskawa-robot/)on ROS Answers. 

> motoman_driver is essentially trajectory based, ie: it consumes trajectories, not individual position setpoints.

I am sending trajectories to my robot. This is done by sending goals to  "/joint_trajectory_action". 

> I'm pretty sure this is the cause of your problem. Setting velocities to zero will lead to stop-and-go behaviour.

I replaced the zero velocities by non-zero velocities corresponding to the diplacement divided by trajectory duration, and I am still having the same problem...

**Comment by gavanderhoorn** [comment] 2021-02-04 11:21
I may not have been clear enough: trajectory based in this case means: from 0-state to 0-state. So from a stopped state (0 velocity and acceleration) to another stopped state (0 velocity and acceleration).

To avoid me misunderstanding you, perhaps you could show us the following:

 - the code you use to generate and send the trajectories
 - an example trajectory (ie: captured using `rostopic echo` on the appropriate `goal` topic of the action server)
 - a wireshark capture of the traffic between the ROS PC and the Yaskawa controller

**Comment by gavanderhoorn** [comment] 2021-02-16 19:00
@iom12: could you comment to let us know whether this is still a problem for you?

if you'd like to continue diagnosing the issue, I'd repeat my request for the additional information I described in my previous comment.

**Comment by gavanderhoorn** [comment] 2021-02-22 16:13
@iom12: I hope you've been able to figure this out. If not, please comment and we can re-open.

You indicated you'd been in touch with Yaskawa France, so perhaps they've been able to help you.

For now, I'll close this.

**Closed as completed by gavanderhoorn** 2021-02-22 16:13 UTC
Labels: more-info-needed
